### ISSUE TITLE
Reenable basic support for i18n locales in docs portal

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/docsgen#110]
Most chinese (and probably other locales) static pages are currently rendering this (React?) error:

"Cannot destructure property 'versions' of 'n' as it is undefined."

AC:
- Static pages should render the English content by default.
- Overridden pages in `i18n/...` should render the appropriate locale version.

This ticket is High Priority - related to https://github.com/eosnetworkfoundation/devrel/issues/213

**Comment by ericpassmore** [comment]
During the last redesign JS code was added to generate the Right Side Bar, and that code needed to parse the URL. That parsing broke when the local was added to the URL.

**Comment by ericpassmore** [comment]
Removing the custom theme created during the redesign solved the issue. Something in the custom theme created by contract developer is preventing multi-local support. 

```bash
###
# Install Theme Updates
Install_DOC6S_Theme() {
  #cp -r "${SCRIPT_DIR:?}/../web/docusaurus/src/components" "${ARG_BUILD_DIR:?}/devdocs/src/"
  #cp -r "${SCRIPT_DIR:?}/../web/docusaurus/src/css" "${ARG_BUILD_DIR:?}/devdocs/src/"
  #cp -r "${SCRIPT_DIR:?}/../web/docusaurus/src/hooks" "${ARG_BUILD_DIR:?}/devdocs/src/"
  #cp -r "${SCRIPT_DIR:?}/../web/docusaurus/src/pages" "${ARG_BUILD_DIR:?}/devdocs/src/"
  #cp -r "${SCRIPT_DIR:?}/../web/docusaurus/src/theme" "${ARG_BUILD_DIR:?}/devdocs/src/"
  cp -r "${SCRIPT_DIR:?}/../web/docusaurus/static" "${ARG_BUILD_DIR:?}/devdocs/"
}
```
<img width="1746" alt="Screenshot 2023-04-20 at 5 12 22 PM" src="https://user-images.githubusercontent.com/6685407/233512053-36d1bc80-f353-4ce7-8ef9-df2ce7d176c8.png">

**Comment by ericpassmore** [comment]
Works when `CustomTOC` is removed. See image below for image of component.
<img width="385" alt="CustomTOC" src="https://user-images.githubusercontent.com/6685407/233526297-0e144206-d364-4c67-a963-bc4a7f8c1a25.png">

Page working with `CustomTOC`
<img width="1079" alt="Screenshot 2023-04-20 at 7 26 32 PM" src="https://user-images.githubusercontent.com/6685407/233526473-c59709c3-0384-48f6-b96f-e085587a9d68.png">

**Comment by ericpassmore** [comment]
Fixed, one interesting thing the right side TOC drop down switches to "Next" for non-en locals. The en-local has "latest". Not sure how this drop down is used, it was custom work as part of the redesign. 
<img width="404" alt="Screenshot 2023-04-21 at 3 45 02 PM" src="https://user-images.githubusercontent.com/6685407/233745795-99cb9eba-8ca6-4d52-b8bb-77923979a9ec.png">
<img width="398" alt="Screenshot 2023-04-21 at 3 45 10 PM" src="https://user-images.githubusercontent.com/6685407/233745804-d94aef28-8225-4d0e-b23d-afc55533b063.png">

**Comment by lparisc** [comment]
> Fixed, one interesting thing the right side TOC drop down switches to "Next" for non-en locals. The en-local has "latest". Not sure how this drop down is used, it was custom work as part of the redesign.

The same version drop-down should be used for all locales. I'll create another ticket to address this later.
