### ISSUE TITLE
Find root cause for account's guide file/sidebar render issue

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/docsgen#111]
This issue seems to have resolved by itself (or just pure luck) at some point after several commits to `staging`. However, not knowing the root cause might potentially jeopardize future doc deployments since the issue might reappear.

Problem:
https://github.com/eosnetworkfoundation/docs/blob/repro-devrel%23198/docs/20_smart-contracts/10_getting-started/20_accounts/index.md

renders like this:

![accounts-title](https://user-images.githubusercontent.com/1623413/221766024-ff9cc3ba-463e-44e2-a65c-f0297de1bee1.png)

To reproduce at the point where it happened:

1. checkout `repro-devrel#198` branch from `docsgen` .
2. build docs using `-s` (staging) option to local build folder of choice.
3. cd to `devdocs`  folder within build folder and launch web server via `npm`.
4. navigate to http://localhost:3000/docs/latest/smart-contracts/getting-started/Accounts

**Comment by ericpassmore** [comment]
## Summary 
Content error. Found an additional, empty tag heading at the top of the document. Will close as `Won't Fix`
```
---

---
```
<img width="1328" alt="Screenshot 2023-04-28 at 7 36 57 AM" src="https://user-images.githubusercontent.com/6685407/235177706-4c24d09a-73a5-4828-84e9-8d1303d647f2.png">

After removing the empty tag heading, rebuild and verified correct presentation.
<img width="1226" alt="Screenshot 2023-04-28 at 7 39 44 AM" src="https://user-images.githubusercontent.com/6685407/235178030-9fb74da1-457e-424d-8d57-24c3d5027ee4.png">
