### ISSUE TITLE
Staging site crashes on Android mobile device

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/docsgen#115]
Visiting \<staging-site\>/docs/latest/smart-contracts/ on an Android device yields the following error message:

![image](https://user-images.githubusercontent.com/1623413/234637761-6efcd40b-dcf8-4ba5-b573-bdc8a1ccb3e2.png)

Visiting the production site https://docs.eosnetwork.com/docs/latest/smart-contracts/ from an Android doesn't yield the error.

**Comment by lparisc** [comment]
It also seems to crash on a desktop after a resize.

**Comment by ericpassmore** [comment]
addressed in PR #116 
reviewed the code fix and tested, marking fixed
