### ISSUE TITLE
EOS EVM how to transfer your EOS

### ISSUE THREAD

**Issue by iamveritas** [eosnetworkfoundation/docsgen#132]
Build "How To Transfer EOS EVM Tokens" and cover the move of tokens from/to EOS EVM <-> CEX/DEX using the EOS EVM bridge and also mentioning the multi-bridge as well (which now is broken).

Notes from Zack:

It is very much needed.

I think the guide also needs a complementary guide on how to create an EOS account (both free and paid options). Perhaps we already have that documented though.

I think it's important to cover both Anchor and Wombat.
For EVM users, Wombat is the simplest path because 

1. it is a Chrome extension rather than desktop client. This is familiar to MetaMask users.
2. it allows you to create a free EOS account (no credit card or app store payment needed)
3. Like Anchor, Wombat also covers used resources and I know they're following Wharf closely.
4. Let's you make an EOS transfer to CEX from within wallet interface instead of being more of a signer/authenticator like Anchor. It's a more familiar experience for most users

link from Lliam:
https://drive.google.com/drive/folders/1Ms25cdd6Q9Ba2iCMwJVaSoO5_iRZ4VMT?usp=sharing

**Comment by nsjames** [comment]
Done in recent ticket, discarding this
