### ISSUE TITLE
Create "How to create EOS account on mainnet"

### ISSUE THREAD

**Issue by iamveritas** [eosnetworkfoundation/docsgen#79]
![Image](https://user-images.githubusercontent.com/11767353/209087171-a4ecd60d-e817-49fd-a12c-d88c1f2666b8.png)

source: https://t.me/c/1632437343/1388

**Comment by ericpassmore** [comment]
should this issue be moved and tracked in eosnetworkfoundation/docs ?

**Comment by nsjames** [comment]
Closing as this is being handled by marcom and directed at the general users of the EOS blockchain. 

Once that tutorial is live, we should link to it from the docs in a section aimed at pushing contracts to production (mainnet)
