### ISSUE TITLE
Move docs repo images to central location 

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/docsgen#84]
To simplify the install scripts we should move the image locations. This applies to 
- docs/01_overview
- docs/02_getting-started
- docs/04_protocol

1) Create a new central directory `images` under [docs](https://github.com/eosnetworkfoundation/docs/tree/main/docs)
2) Permanently  all `images` from each directory above to `docs/images`
3) Permanently correct all the markdown files to reference images under path  `/docs/images`
4) During the `docsgen` build create a new directory under Docusaurus `IMG_DIR="${ARG_BUILD_DIR:?}"/devdocs/static/docs/images`
5) During the Docusaurus build process copy images from `docs` github into path listed in 4

**Comment by lparisc** [comment]
Steps 1,2,3 were done in PRs eosnetworkfoundation/docs#44 and eosnetworkfoundation/docs#46
Steps 4,5 were in PR #87
