### ISSUE TITLE
Add math equations rendering support to docusaurus

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/docsgen#85]
Markdown documents that contain LaTeX blocks are not rendered. For example:
- https://docs.eosnetwork.com/docs/latest/protocol/accounts_and_permissions/
(browse to 2. Accounts)

**Comment by ericpassmore** [comment]
Need to follow these steps to add the plugins

https://docusaurus.io/docs/markdown-features/math-equations
