### ISSUE TITLE
Fix docs staging and production builds

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/docsgen#98]
Staging site has been broken since UTC Wed Feb 22 11:00:02 AM.

Local build throws this error:

```
Error: Markdown link URL is mandatory in "eosdocs/DUNE/index.md" file (title: https://github.com/kislyuk/argcomplete#global-completion, line: 647).
[ERROR] Client bundle compiled with errors therefore further build is impossible.
FATAL: npm run build failed exiting
```

**Comment by lparisc** [comment]
Error:
https://github.com/AntelopeIO/DUNE/commit/a578d527c728039289f9fabf7edb9224dd6a026a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R647

Solution:
pulling from latest DUNE release tag, not `main`, should fix the issue.

**Comment by nsjames** [comment]
We will handle #101 as a separate ticket, it isn't required for this
